<a href="https://colab.research.google.com/github/MysticCelestia8/MachineLearning/blob/main/Data_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing

## Importing the libraries

In [44]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Importing Dataset

In [45]:
data_set = pd.read_csv("Covid_Data_new.csv")
X = data_set.iloc[:,:-1].values
Y = data_set.iloc[:,-1].values

In [46]:
print(X)

[[10.0 'Normal' 'no' 'no' 97.0]
 [12.0 'Normal' 'no' 'no' 97.0]
 [15.0 'Normal' 'no' 'no' 94.0]
 [10.0 'Normal' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 94.0]
 [12.0 'Moderate' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 93.0]
 [15.0 'Moderate' 'no' 'no' 92.0]
 [18.0 'Moderate' 'no' 'no' 66.0]
 [19.0 'Normal' 'no' 'no' 92.0]
 [20.0 'Normal' 'no' 'no' 93.0]
 [17.0 'Normal' 'no' 'no' 93.0]
 [16.0 'Normal' 'no' 'no' 92.0]
 [18.0 'Normal' 'no' 'no' 93.0]
 [20.0 'Normal' 'no' 'no' 92.0]
 [25.0 'Moderate' 'no' 'no' 93.0]
 [24.0 'Moderate' 'no' 'no' 92.0]
 [26.0 'High' 'no' 'no' 94.0]
 [28.0 'Normal' 'no' 'no' 99.0]
 [29.0 'Normal' 'no' 'no' 93.0]
 [30.0 'Moderate' 'no' 'no' 62.0]
 [19.0 'Normal' 'no' 'no' 89.0]
 [25.0 'Normal' 'no' 'yes' 86.0]
 [26.0 'Normal' 'no' 'no' nan]
 [28.0 'Normal' 'no' 'no' 89.0]
 [30.0 'Moderate' 'yes' 'no' 86.0]
 [35.0 'Moderate' 'no' 'no' 89.0]
 [32.0 'Moderate' 'no' 'yes' 84.0]
 [nan 'Moderate' 'yes' 'no' 90.0]
 [32.0 'Moderate' 'no' 'no' 89.0]
 [35.0 'Modera

In [47]:
print(Y)

['No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes'
 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes'
 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'Yes'
 'Yes' 'No' 'Yes' 'Yes' 'Yes']





## Handling Missing Data

In [48]:
#replacing NaN values with mean values

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan,strategy = 'mean')
imputer.fit(X[:, 0:1])
X[:, 0:1] = imputer.transform(X[:, 0:1]) #similar to x = x+1
X[:, 0:1] = np.round(np.array(X[:, 0:1], dtype=float), decimals=2)

imputer.fit(X[:, 4:5])
X[:, 4:5] = imputer.transform(X[:, 4:5])
X[:, 4:5] = np.round(np.array(X[:, 4:5], dtype=float), decimals=2)

In [49]:
print(X)

[[10.0 'Normal' 'no' 'no' 97.0]
 [12.0 'Normal' 'no' 'no' 97.0]
 [15.0 'Normal' 'no' 'no' 94.0]
 [10.0 'Normal' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 94.0]
 [12.0 'Moderate' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 93.0]
 [15.0 'Moderate' 'no' 'no' 92.0]
 [18.0 'Moderate' 'no' 'no' 66.0]
 [19.0 'Normal' 'no' 'no' 92.0]
 [20.0 'Normal' 'no' 'no' 93.0]
 [17.0 'Normal' 'no' 'no' 93.0]
 [16.0 'Normal' 'no' 'no' 92.0]
 [18.0 'Normal' 'no' 'no' 93.0]
 [20.0 'Normal' 'no' 'no' 92.0]
 [25.0 'Moderate' 'no' 'no' 93.0]
 [24.0 'Moderate' 'no' 'no' 92.0]
 [26.0 'High' 'no' 'no' 94.0]
 [28.0 'Normal' 'no' 'no' 99.0]
 [29.0 'Normal' 'no' 'no' 93.0]
 [30.0 'Moderate' 'no' 'no' 62.0]
 [19.0 'Normal' 'no' 'no' 89.0]
 [25.0 'Normal' 'no' 'yes' 86.0]
 [26.0 'Normal' 'no' 'no' 82.07]
 [28.0 'Normal' 'no' 'no' 89.0]
 [30.0 'Moderate' 'yes' 'no' 86.0]
 [35.0 'Moderate' 'no' 'no' 89.0]
 [32.0 'Moderate' 'no' 'yes' 84.0]
 [45.13 'Moderate' 'yes' 'no' 90.0]
 [32.0 'Moderate' 'no' 'no' 89.0]
 [35.0 'Mo

## Encoding Categorical Data

### Encoding independent variables

In [50]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [51]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1,2,3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [52]:
print(X)

[[0.0 0.0 1.0 1.0 0.0 1.0 0.0 10.0 97.0]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 12.0 97.0]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 15.0 94.0]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 10.0 97.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 13.0 94.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 12.0 97.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 13.0 93.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 15.0 92.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 18.0 66.0]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 19.0 92.0]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 20.0 93.0]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 17.0 93.0]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 16.0 92.0]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 18.0 93.0]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 20.0 92.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 25.0 93.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 24.0 92.0]
 [1.0 0.0 0.0 1.0 0.0 1.0 0.0 26.0 94.0]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 28.0 99.0]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 29.0 93.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 30.0 62.0]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 19.0 89.0]
 [0.0 0.0 1.0 1.0 0.0 0.0 1.0 25.0 86.0]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 26.0 82.07]
 [0.0 0.0 1.0 1

### Encoding dependent variables

In [53]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(Y)

In [54]:
print(Y)

[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1]


## Splitting data into Test set & Training Set


In [55]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train,Y_test = train_test_split(X,Y,test_size=0.4,random_state=42)

In [56]:
print(X_train)


[[1.0 0.0 0.0 0.0 1.0 0.0 1.0 54.0 70.0]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 29.0 93.0]
 [1.0 0.0 0.0 0.0 1.0 0.0 1.0 78.0 71.0]
 [1.0 0.0 0.0 0.0 1.0 1.0 0.0 36.0 90.0]
 [0.0 1.0 0.0 0.0 1.0 1.0 0.0 30.0 86.0]
 [1.0 0.0 0.0 0.0 1.0 0.0 1.0 50.0 77.0]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 18.0 93.0]
 [1.0 0.0 0.0 1.0 0.0 0.0 1.0 69.0 53.0]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 10.0 97.0]
 [1.0 0.0 0.0 1.0 0.0 1.0 0.0 26.0 94.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 18.0 66.0]
 [1.0 0.0 0.0 0.0 1.0 0.0 1.0 62.0 69.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 13.0 93.0]
 [1.0 0.0 0.0 1.0 0.0 1.0 0.0 40.0 92.0]
 [1.0 0.0 0.0 0.0 1.0 0.0 1.0 84.0 75.0]
 [1.0 0.0 0.0 0.0 1.0 0.0 1.0 76.0 80.0]
 [1.0 0.0 0.0 0.0 1.0 0.0 1.0 81.0 75.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 25.0 93.0]
 [0.0 1.0 0.0 1.0 0.0 0.0 1.0 32.0 84.0]
 [1.0 0.0 0.0 0.0 1.0 0.0 1.0 56.0 77.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 35.0 89.0]
 [1.0 0.0 0.0 0.0 1.0 0.0 1.0 63.0 66.0]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 28.0 89.0]
 [1.0 0.0 0.0 0.0 1.0 1.0 0.0 56.0 76.0]
 [1.0 0.0 0.0 0.

In [57]:
print (X_test)

[[0.0 0.0 1.0 1.0 0.0 0.0 1.0 25.0 86.0]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 10.0 97.0]
 [1.0 0.0 0.0 0.0 1.0 1.0 0.0 68.0 67.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 13.0 94.0]
 [1.0 0.0 0.0 0.0 1.0 1.0 0.0 59.0 68.0]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 28.0 99.0]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 20.0 93.0]
 [1.0 0.0 0.0 0.0 1.0 1.0 0.0 46.0 91.0]
 [1.0 0.0 0.0 0.0 1.0 1.0 0.0 53.0 55.0]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 16.0 92.0]
 [1.0 0.0 0.0 1.0 0.0 1.0 0.0 38.0 75.0]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 19.0 92.0]
 [1.0 0.0 0.0 0.0 1.0 0.0 1.0 94.0 64.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 12.0 97.0]
 [1.0 0.0 0.0 0.0 1.0 0.0 1.0 86.0 71.0]
 [0.0 1.0 0.0 1.0 0.0 0.0 1.0 35.0 92.0]
 [1.0 0.0 0.0 1.0 0.0 0.0 1.0 75.0 72.0]
 [1.0 0.0 0.0 1.0 0.0 1.0 0.0 42.0 92.0]
 [1.0 0.0 0.0 0.0 1.0 0.0 1.0 74.0 75.0]
 [1.0 0.0 0.0 0.0 1.0 0.0 1.0 62.0 68.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 24.0 92.0]
 [0.0 1.0 0.0 1.0 0.0 0.0 1.0 48.0 93.0]
 [1.0 0.0 0.0 1.0 0.0 1.0 0.0 58.0 70.0]
 [0.0 1.0 0.0 0.0 1.0 1.0 0.0 45.13 90.0]
 [0.0 1.0 0.0 1

In [58]:
print(Y_train)

[1 0 1 0 0 1 0 1 0 0 1 1 0 0 1 1 1 0 0 1 0 1 0 1 1 0 0 0 1 1 0 1 1 0 1 0 0
 0 1 0 0 1]


In [59]:
print(Y_test)

[0 0 1 0 1 0 0 0 1 0 1 0 1 0 1 0 1 0 1 1 0 0 1 0 0 0 1 1]


## Feature Scaling

In [60]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler();
X_train[:, 8:] = sc.fit_transform(X_train[:, 8:])
X_test[:, 8:] = sc.fit_transform(X_test[:, 8:])

In [61]:
print(X_train)

[[1.0 0.0 0.0 0.0 1.0 0.0 1.0 54.0 -1.0679677789952886]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 29.0 1.0285974952735135]
 [1.0 0.0 0.0 0.0 1.0 0.0 1.0 78.0 -0.9768127670705581]
 [1.0 0.0 0.0 0.0 1.0 1.0 0.0 36.0 0.755132459499322]
 [0.0 1.0 0.0 0.0 1.0 1.0 0.0 30.0 0.3905124118003998]
 [1.0 0.0 0.0 0.0 1.0 0.0 1.0 50.0 -0.4298826955221749]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 18.0 1.0285974952735135]
 [1.0 0.0 0.0 1.0 0.0 0.0 1.0 69.0 -2.6176029817157076]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 10.0 1.3932175429724356]
 [1.0 0.0 0.0 1.0 0.0 1.0 0.0 26.0 1.119752507198244]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 18.0 -1.4325878266942107]
 [1.0 0.0 0.0 0.0 1.0 0.0 1.0 62.0 -1.159122790920019]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 13.0 1.0285974952735135]
 [1.0 0.0 0.0 1.0 0.0 1.0 0.0 40.0 0.937442483348783]
 [1.0 0.0 0.0 0.0 1.0 0.0 1.0 84.0 -0.612192719371636]
 [1.0 0.0 0.0 0.0 1.0 0.0 1.0 76.0 -0.15641765974798333]
 [1.0 0.0 0.0 0.0 1.0 0.0 1.0 81.0 -0.612192719371636]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 25.0 1.0285974952735135]
 [0.0 

In [62]:
print(X_test)

[[0.0 0.0 1.0 1.0 0.0 0.0 1.0 25.0 0.2755638128116614]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 10.0 1.168970700664207]
 [1.0 0.0 0.0 0.0 1.0 1.0 0.0 68.0 -1.2675935389336443]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 13.0 0.9253142767044217]
 [1.0 0.0 0.0 0.0 1.0 1.0 0.0 59.0 -1.1863747309470494]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 28.0 1.331408316637397]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 20.0 0.8440954687178267]
 [1.0 0.0 0.0 0.0 1.0 1.0 0.0 46.0 0.6816578527446366]
 [1.0 0.0 0.0 0.0 1.0 1.0 0.0 53.0 -2.2422192347727847]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 16.0 0.7628766607312316]
 [1.0 0.0 0.0 1.0 0.0 1.0 0.0 38.0 -0.617843075040884]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 19.0 0.7628766607312316]
 [1.0 0.0 0.0 0.0 1.0 0.0 1.0 94.0 -1.5112499628934295]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 12.0 1.168970700664207]
 [1.0 0.0 0.0 0.0 1.0 0.0 1.0 86.0 -0.9427183069872642]
 [0.0 1.0 0.0 1.0 0.0 0.0 1.0 35.0 0.7628766607312316]
 [1.0 0.0 0.0 1.0 0.0 0.0 1.0 75.0 -0.8614994990006691]
 [1.0 0.0 0.0 1.0 0.0 1.0 0.0 42.0 0.7628766607312316]
 [1.0 0