<a href="https://colab.research.google.com/github/MysticCelestia8/MachineLearning/blob/main/Intro_to_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
import math as m

In [2]:
demo = [10,20,'30']
np.array(demo)

array(['10', '20', '30'], dtype='<U21')

In [3]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [5]:
np.ones((3,4),int) #2D Array

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [7]:
np.ones((3,4,5),int) #3D Array

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [6]:
x1 = np.ones(5)

x1[2] = 3 #converts int 3 automatically to float and puts it in the array of floats

print(x1)

[1. 1. 3. 1. 1.]


In [3]:
x = np.array([1,2,3])
y = np.array([4,5,6])
x = x + 10
print(x)
print(x+y)

[11 12 13]
[15 17 19]


In [4]:
x = np.array([12,13,14,15,16])
print(x.mean());
print(x.sum());

14.0
70


In [10]:
#To Calculate the distance of 2 coordinates (root)((y2-y1)^2 + (x2-x1)^2)

p1 = np.array([3,3,3])
p2 = np.ones(3)

val = ((p2-p1)**2).sum();


print(m.sqrt(val))

3.4641016151377544


In [12]:
#Calculate the Euclidean norm, the straight line distance from the origin to the point represented by the vector
#Standard deviation multiplied by (root)n

pts = np.array([2,3,4,5])
val1 = ((pts - pts.mean())**2).sum()

print(m.sqrt(val1))

2.23606797749979


In [13]:
#Dot product of two arrays

x1 = np.array([1,2,3])
x2 = np.array([2,3,4]);
print(x1.dot(x2))

20
